class FlowMatchPresetConfig:
    # Định nghĩa sẵn database cấu hình của từng model ở đây để dễ quản lý/thêm bớt
    MODEL_PRESETS = {
        "AceStep 1.5": {
            "num_train_timesteps": 1000,
            "use_dynamic_shifting": False,
            "shift": 3.0,
        },
        "Boogu-Image": {
            "num_train_timesteps": 1000,
            "use_dynamic_shifting": False,
            "shift": 3.0,
        },
        "Chroma": {
            "base_image_seq_len": 256,
            "base_shift": 0.5,
            "max_image_seq_len": 4096,
            "max_shift": 1.15,
            "num_train_timesteps": 1000,
            "shift": 3.0,
            "use_dynamic_shifting": True
        },
        "Chroma Radiance": {
            "base_image_seq_len": 256,
            "base_shift": 0.5,
            "max_image_seq_len": 4096,
            "max_shift": 1.15,
            "num_train_timesteps": 1000,
            "shift": 3.0,
            "use_dynamic_shifting": True
        },
        "Ernie-Image": {
            "base_image_seq_len": 256,
            "base_shift": 0.5,
            "invert_sigmas": False,
            "max_image_seq_len": 4096,
            "max_shift": 1.15,
            "num_train_timesteps": 1000,
            "shift": 3.0,
            "shift_terminal": None,
            "stochastic_sampling": False,
            "time_shift_type": "exponential",
            "use_beta_sigmas": False,
            "use_dynamic_shifting": False,
            "use_exponential_sigmas": False,
            "use_karras_sigmas": False,
        },
        "F-Light": {
            "base_image_seq_len": 256,
            "base_shift": 0.5,
            "max_image_seq_len": 4096,
            "max_shift": 1.15,
            "num_train_timesteps": 1000,
            "shift": 3.0,
            "use_dynamic_shifting": True
        },
        "Flux.2": {
            "base_image_seq_len": 256,
            "base_shift": 0.5,
            "max_image_seq_len": 4096,
            "max_shift": 1.15,
            "num_train_timesteps": 1000,
            "shift": 3.0,
            "use_dynamic_shifting": True,
        },
        "Flux Kontext": {
            "base_image_seq_len": 256,
            "base_shift": 0.5,
            "max_image_seq_len": 4096,
            "max_shift": 1.15,
            "num_train_timesteps": 1000,
            "shift": 3.0,
            "use_dynamic_shifting": True
        },
        "HiDream": {
            "num_train_timesteps": 1000,
            "shift": 3.0
        },
        "HiDream O1": {
            "num_train_timesteps": 1000,
            "shift": 3.0,
            "use_dynamic_shifting": False,
        },
        "IdeoGram4": {
            "base_image_seq_len": 256,
            "base_shift": 0.5,
            "invert_sigmas": False,
            "max_image_seq_len": 4096,
            "max_shift": 1.15,
            "num_train_timesteps": 1000,
            "shift": 1.0,
            "shift_terminal": None,
            "stochastic_sampling": False,
            "time_shift_type": "exponential",
            "use_beta_sigmas": False,
            "use_dynamic_shifting": False,
            "use_exponential_sigmas": False,
            "use_karras_sigmas": False,
        },
        "Krea2": {
            "base_image_seq_len": 256,
            "max_image_seq_len": 6400,
            "base_shift": 0.5,
            "max_shift": 1.15,
            "num_train_timesteps": 1000,
            "shift": 1.0,
            "use_dynamic_shifting": True,
            "time_shift_type": "exponential",
        },
        "LTX 2 | 2.3": {
            "base_image_seq_len": 1024,
            "base_shift": 0.95,
            "invert_sigmas": False,
            "max_image_seq_len": 4096,
            "max_shift": 2.05,
            "num_train_timesteps": 1000,
            "shift": 1.0,
            "shift_terminal": 0.1,
            "stochastic_sampling": False,
            "time_shift_type": "exponential",
            "use_beta_sigmas": False,
            "use_dynamic_shifting": True,
            "use_exponential_sigmas": False,
            "use_karras_sigmas": False,
        },
        "Nucleus": {
            "base_image_seq_len": 256,
            "base_shift": 0.5,
            "invert_sigmas": False,
            "max_image_seq_len": 4096,
            "max_shift": 1.15,
            "num_train_timesteps": 1000,
            "shift": 1.0,
            "shift_terminal": None,
            "stochastic_sampling": False,
            "time_shift_type": "exponential",
            "use_beta_sigmas": False,
            "use_dynamic_shifting": False,
            "use_exponential_sigmas": False,
            "use_karras_sigmas": False
        },
        "PRX Pixel t2i": {
            "num_train_timesteps": 1000,
            "use_dynamic_shifting": False,
            "shift": 3.0,
        },
        "Qwen Image": {
            "base_image_seq_len": 256,
            "base_shift": 0.5,
            "invert_sigmas": False,
            "max_image_seq_len": 8192,
            "max_shift": 0.9,
            "num_train_timesteps": 1000,
            "shift": 1.0,
            "shift_terminal": 0.02,
            "stochastic_sampling": False,
            "time_shift_type": "exponential",
            "use_beta_sigmas": False,
            "use_dynamic_shifting": True,
            "use_exponential_sigmas": False,
            "use_karras_sigmas": False,
        },
        "Z-Image | Turbo": {
            "num_train_timesteps": 1000,
            "use_dynamic_shifting": False,
            "shift": 3.0,
        },
        "Zeta Chroma": {
            "num_train_timesteps": 1000,
            "use_dynamic_shifting": False,
            "shift": 3.0,
        },
        "Flex 2": {
            "base_image_seq_len": 256,
            "base_shift": 0.5,
            "max_image_seq_len": 4096,
            "max_shift": 1.15,
            "num_train_timesteps": 1000,
            "shift": 3.0,
            "use_dynamic_shifting": True
        },
        "CogView 4": {
            "base_image_seq_len": 256,
            "base_shift": 0.25,
            "invert_sigmas": False,
            "max_image_seq_len": 4096,
            "max_shift": 0.75,
            "num_train_timesteps": 1000,
            "shift": 1.0,
            "shift_terminal": None,
            "time_shift_type": "linear",
            "use_beta_sigmas": False,
            "use_dynamic_shifting": True,
            "use_exponential_sigmas": False,
            "use_karras_sigmas": False
        },
        "Wan 2.1 | 2.2": {
            "num_train_timesteps": 1000,
            "use_dynamic_shifting": False,
            "shift": 3.0,
        },
    }